### ISSUE TITLE
ShellCmdBuilder should derive top level paths from aggregation of all steps paths

### ISSUE THREAD

**Issue by skilgoreT** [hipponot/bit#26]
At the moment you have to specify two sets of paths for ShellCommandBuilder - the outer controls the watch trigger the steps paths control step skip.. 

The is redundant (example below) we should derive the outer paths from the steps paths

```yaml
---
name: xlr8_gql
build_ver: BW2
type: in-house
builder: ShellCmdBuilder
paths:
  - src/**/*
  - gql/*.gql
steps:
  - cmd: yarn install
    paths:
      - ./node_modules
      - package.json
  - cmd: ./schema-build.rb
    paths:
      - ./gql/*.gql
  - cmd: npx tsc --module commonjs && npx rollup -c rollup.config.ts && npx yalc push
    paths:
      - ./src/**/*
```
